/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default']
    CheckboxGroup: typeof import('./../components/CheckboxGroup/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    Error: typeof import('./../views/Error.vue')['default']
    NoMore: typeof import('./../components/ScrollLoad/NoMore.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    Picker: typeof import('./../components/Picker/index.vue')['default']
    RadioGroup: typeof import('./../components/RadioGroup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollLoad: typeof import('./../components/ScrollLoad/index.vue')['default']
    Selector: typeof import('./../components/Selector/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Tooltip: typeof import('./../components/Tooltip/index.vue')['default']
  }
}
